version: "3.7"
services:
  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=stocks
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=bruno
      - MYSQL_PASSWORD=password
    ports: 
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    restart: always
    entrypoint: 'bash ./entrypoint.sh'
    depends_on: 
      - db
    volumes: 
      - ${PWD}:/code
volumes:
  db-data: